import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {normalizeReasoningResult} from '../src/services/result-normalizer.ts';
import {parseNativePersonalMap,mapProgress} from '../src/ixo.ts';

const good={answer:'synthetic',context_used:[],assumptions:[],missing_information:[],why_context_changed_answer:'',evidence_refs:[]};
assert.equal(normalizeReasoningResult(JSON.stringify(good)).answer,'synthetic');
assert.equal(normalizeReasoningResult('  '+JSON.stringify(good)+'  ').answer,'synthetic');
assert.equal(normalizeReasoningResult('```json\n'+JSON.stringify(good)+'\n```').answer,'synthetic');
assert.equal(normalizeReasoningResult('wrapper\n'+JSON.stringify({...good,answer:'brace } inside string'})+'\nend').answer,'brace } inside string');
assert.throws(()=>normalizeReasoningResult('before '+JSON.stringify(good)+' between '+JSON.stringify(good)+' after'),/unreadable result/);
assert.throws(()=>normalizeReasoningResult('plain markdown answer'),/unreadable result/);
assert.throws(()=>normalizeReasoningResult('{"answer":"broken",}'),/unreadable result/);
assert.throws(()=>normalizeReasoningResult('[1,2,3]'),/unreadable result/);

const root=process.cwd();
const today=readFileSync(join(root,'src/components/TodayView.tsx'),'utf8');
const mirror=readFileSync(join(root,'src/components/MirrorView.tsx'),'utf8');
const ask=readFileSync(join(root,'src/components/AskIxoView.tsx'),'utf8');
const decide=readFileSync(join(root,'src/components/DecisionLab.tsx'),'utf8');
const reasoning=readFileSync(join(root,'src/services/reasoning.ts'),'utf8');
const runStatus=readFileSync(join(root,'api/ixo/run-status.js'),'utf8');
const session=readFileSync(join(root,'api/ixo/session.js'),'utf8');
const app=readFileSync(join(root,'src/App.tsx'),'utf8');
const css=readFileSync(join(root,'src/styles.css'),'utf8');

assert.match(today,/autoStarted=useRef\(false\)/);
assert.match(today,/useEffect\(\(\)=>\{if\(autoStarted\.current\)return;autoStarted\.current=true;void run\(\)\},\[\]\)/);
assert.doesNotMatch(today,/profile_revision[^\n]*useEffect|useEffect[^\n]*profile_revision/);
assert.match(mirror,/autoStarted=useRef\(false\)/);
assert.match(mirror,/useEffect\(\(\)=>\{if\(autoStarted\.current\)return;autoStarted\.current=true;void run\(\)\},\[\]\)/);
assert.match(ask,/onClick=\{ask\}/);
assert.match(ask,/Re-read result/);
assert.match(ask,/rereadReasoning\(recoverableJob\)/);
assert.match(reasoning,/recover:'completed'/);
assert.doesNotMatch(reasoning,/rereadReasoning[\s\S]{0,500}startReasoning/);
assert.match(decide,/onClick=\{analyze\}/);
assert.match(runStatus,/req\.query\?\.recover\|\|''\)==='completed'/);
assert.match(runStatus,/req\.query\?\.diagnostic\|\|''\)==='structure'/);
assert.doesNotMatch(runStatus,/console\./);
assert.match(session,/\^\[0-9\]\{6\}\$/);
assert.match(session,/confirmed:true/);
assert.doesNotMatch(session,/verified_email_present/);
const confirmBlock=app.slice(app.indexOf('const confirmVerification='),app.indexOf('const retryPersonalMap='));
assert.equal((confirmBlock.match(/await fetchMap\(\)/g)||[]).length,1);
assert.doesNotMatch(confirmBlock,/startReasoning|\/api\/ixo\/reason/);
assert.match(app,/Not now/);
assert.doesNotMatch(app,/Ã|â€|Â/);
for(const state of ['LOADING','READY','PARTIAL','AUTH_REQUIRED','ERROR'])assert.match(app,new RegExp(state));
assert.match(css,/\.mirrorGrid\{display:grid;grid-template-columns:minmax\(0,1fr\)/);
assert.match(css,/@media\(max-width:900px\)/);
const nativeMap=parseNativePersonalMap({areas:[{id:'work',covered:true},{id:'family',covered:true},{id:'rest',covered:true},{id:'values',covered:true}]});
assert.equal(nativeMap.covered.length,4);assert.equal(mapProgress(nativeMap).label,'4/10');
assert.equal(nativeMap.source,'native');
console.log('REGRESSION PASS: normalization, lifecycle, verification, recovery and encoding gates passed.');
