import {useState} from 'react'; import Map from './Map'; import {cloneSeed,questions,categories,labels,aspects,aspectLabels,count,coverage,type MapState,type Ref} from './ixo';
type Stage='hero'|'demo'|'done'|'connect';
export default function App(){const [map,setMap]=useState<MapState>(cloneSeed);const [stage,setStage]=useState<Stage>('hero');const [qi,setQi]=useState(0);const [answer,setAnswer]=useState('');const [phase,setPhase]=useState<'ask'|'thinking'|'reveal'>('ask');const [learned,setLearned]=useState<Ref[]>([]);const [prev,setPrev]=useState(27);
const reset=()=>{setMap(cloneSeed());setQi(0);setAnswer('');setPhase('ask');setLearned([]);setStage('hero')};
const send=()=>{const q=questions[qi];if(!q)return;setPrev(coverage(map));setPhase('thinking');setTimeout(()=>{const n=structuredClone(map) as MapState;const l:Ref[]=[];q.fills.forEach(([category,aspect])=>{const c=category as keyof MapState,a=aspect as any;if(!n[c].includes(a)){n[c].push(a);l.push({category:c,aspect:a})}});setMap(n);setLearned(l);setAnswer('');if(qi===questions.length-1){setStage('done')}else{setQi(qi+1);setPhase('reveal')}},1100)};
return <main><div className="veil"/><header><div className="logo"><span className="my">MY</span><span className="ixo">iXo</span></div><div className="demo">EXECUTIVE DEMO</div></header><div className="wrap">
{stage==='hero'&&<section className="hero"><div><div className="eyebrow">PERSONAL INTELLIGENCE, MADE VISIBLE</div><h1>BUILD YOUR <em>iXo</em></h1><p className="lead">Turn what iXo knows about you into an intelligent personal operating system.</p><div className="stat"><strong>{coverage(map)}%</strong><div><b>INFORMATION COVERAGE</b><p>iXo currently understands {count(map)} of 30 dimensions of you.</p></div></div><div className="actions"><button className="primary" onClick={()=>setStage('demo')}>Complete My Map →</button><button onClick={()=>setStage('demo')}>Executive Demo</button><button onClick={()=>setStage('connect')}>Connect My iXo</button></div><p className="note">Coverage measures how much iXo understands about you — never a rating of your life.</p></div><Map map={map}/></section>}
{stage==='demo'&&<section className="flow"><div className="panel">{phase==='thinking'?<div className="center"><div className="thinking">Understanding…</div><div className="scan"/></div>:phase==='reveal'?<div className="center"><div className="eyebrow">PERSONAL MAP UPDATED</div><h2>iXo learned {learned.length} new things about you</h2><div className="jump">{prev}% → {coverage(map)}%</div><div className="learned">{learned.map(x=><div key={x.category+x.aspect}><b>{labels[x.category]}</b> · {aspectLabels[x.aspect]}</div>)}</div><button className="primary" onClick={()=>setPhase('ask')}>Continue →</button></div>:<><div className="eyebrow">{count(map)} OF 30 DIMENSIONS UNDERSTOOD</div><h2>{questions[qi].prompt}</h2>{'helper' in questions[qi]&&<p>{questions[qi].helper}</p>}<div className="chips">{questions[qi].chips.map(c=><button key={c} onClick={()=>setAnswer(c)} className={answer===c?'selected':''}>{c}</button>)}</div><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Answer in your own words, or pick a thought-starter above…"/><div className="actions"><button className="primary" onClick={send}>Send to iXo →</button><button onClick={()=>{setQi(Math.min(qi+1,questions.length-1));setAnswer('')}}>Skip</button></div></>}</div><Map map={map} highlight={learned}/></section>}
{stage==='done'&&<section className="finish"><Map map={map} highlight={learned}/><div className="eyebrow">PERSONAL MAP COMPLETE</div><h2>Your iXo knows more than it did 10 minutes ago.</h2><p>10 areas. 30 dimensions. One continuously evolving understanding of you.</p><button className="primary" onClick={()=>setStage('hero')}>Enter iXo →</button><button onClick={reset}>Reset demo</button></section>}
{stage==='connect'&&<section className="panel connect"><div className="eyebrow">CONNECT MY iXo</div><h2>Integration-ready — not connected</h2><p>Live connection is intentionally not active in this executive prototype. Production credentials will stay server-side; this experience will never ask users for API keys, cookies, bearer tokens or passwords.</p><button onClick={()=>setStage('hero')}>← Back</button></section>}
<section className="how"><div className="eyebrow">THE INTELLIGENCE LOOP</div><h2>One conversation. A clearer picture.</h2><div className="steps">{[['01','Adaptive questioning','One high-information question at a time.'],['02','Context & memory','Answers are interpreted against what iXo already knows.'],['03','Confirmed dimensions','Situation, priorities and goals illuminate as context becomes clear.'],['04','Living Personal Map','The map evolves as you do — it is never a life score.']].map(x=><div><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section><footer>MY iXo · Executive prototype · Synthetic demo data only</footer></div></main>}